---
abstract: "Minimalistic integration of Mozillas \"Persona\" authentication system in Mojolicious apps"
author:
  - 'Heiko Jansen <hjansen@cpan.org>'
  - 'Moritz Lenz <moritz@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-MozPersona
requires:
  IO::Socket::SSL: 1.75
  Mojolicious: 2.00
  Mozilla::CA: 20130114
resources:
  repository: https://github.com/heikojansen/mojolicious-plugin-mozpersona.git
version: 0.04
