---
abstract: "Minimalistic integration of Mozillas \"Persona\" authentication system in Mojolicious apps"
author:
  - 'Heiko Jansen <hjansen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-MozPersona
requires:
  IO::Socket::SSL: 1.75
  Mozilla::CA: 20130114
version: 0.01
